spring:
  application:
    name: worldcup

  datasource:
    url: jdbc:mysql://localhost:3306/worldcup_db
    username: springstudent
    password: Springstudent3692@#
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true

spring-doc:
  swagger-ui:
    enabled: true